/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gamer
 */
public class DS extends javax.swing.JFrame {

    /**
     * Creates new form DS
     */
    public DS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jli1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTENTS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 32, 165, 26);

        jli1.setBackground(new java.awt.Color(153, 153, 255));
        jli1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jli1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "<html><body><u>UNIT - 1</u></body></html>", " ", "<html><body><u>UNIT - 2</u></body></html>", " ", "<html><body><u>UNIT - 3</u></body></html>" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jli1.setPreferredSize(new java.awt.Dimension(50, 108));
        jScrollPane1.setViewportView(jli1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(670, 120, 130, 170);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OPEN");
        jButton1.setPreferredSize(new java.awt.Dimension(89, 57));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 390, 167, 57);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("* Please Select The Unit And Click Open");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 471, 230, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Risav Chaudhary\\Pictures\\ds.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int a = jli1.getSelectedIndex();
        if (a==0)
        {
            try
            {
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"F:\\Semester 3\\Data structures\\Unit1.pptx");
            }
            catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e);
        }
        }
 else if (a==1)
        {
            try
            {
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"F:\\Semester 3\\Data structures\\Unit2.pptx");
            }
            catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e);
        }
        }
 else if (a==0)
        {
            try
            {
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler "+"F:\\Semester 3\\Data structures\\Unit3.pptx");
            }
            catch (Exception e)
                    {
                        JOptionPane.showMessageDialog(null,e);
        }
        }
 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jli1;
    // End of variables declaration//GEN-END:variables
}
